### ISSUE TITLE
Gen status flags implementation

### ISSUE THREAD

**Issue by padeken** [Aachen-3A/PxlSkimmer#12]
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD2015#MC_Truth

that would be nice to have

**Comment by padeken** [comment]
info from Sebastian:
sherpa has mupitz info in the status infos.
probably only pythia 8 works

**Comment by thuer** [comment]
addition: At least Sherpa knows how to fill HepMC infos...
The information in these flags have to be taken cautiously even for pythia 8, the logic behind mother/daughter assignments are a bit dubious.

**Comment by serdweg** [comment]
These features are now included, see commits: https://github.com/Aachen-3A/PxlSkimmer/commit/93318ef94619b67143588c12af92ee77d5720a77 and https://github.com/Aachen-3A/PxlSkimmer/commit/099efe011e1c44edf87f4e5189b4a7de067edf3f
