### ISSUE TITLE
PxlSkimmer_miniAOD_cfi: Why are jets still called AK5?

### ISSUE THREAD

**Issue by AndreasAlbert** [Aachen-3A/PxlSkimmer#16]
line 60ff:
"slimmedJetsAK8" are correctly saved as "AK8" in the skimmer.
"slimmedJets", which I believe to be AK4, are saved as "AK5". 

Is there a reason for this? If not, I will change it.

**Comment by serdweg** [comment]
We have seen this also, it seems that Klaas forgot to change it. So you can change it.

**Comment by padeken** [comment]
Yes I have fixed it. sorry I forgot to push
