### ISSUE TITLE
Include the L3 objects in the skimmer output

### ISSUE THREAD

**Issue by serdweg** [Aachen-3A/PxlSkimmer#2]
At the moment there is no possibility to include the L3 objects in the skimmer output. This has to be changed as they are used for trigger studies.

**Comment by serdweg** [comment]
I included the L3 objects in the TrigEventView, but it would be nice if somebody can have a look at the corresponding code (lines 1388-1409 in the dev branch). This is all based on the example at:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD#Trigger
The used object is documented at:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePATTrigger#TriggerObjectStandAlone.
So it would be nice if somebody could have a look at this 20 lines and get back to me.

**Comment by padeken** [comment]
I checked it looks ok!
