### ISSUE TITLE
Choose the datastreams automatic according to the runOnData flag

### ISSUE THREAD

**Issue by serdweg** [Aachen-3A/PxlSkimmer#22]
At the moment this has to be done by hand, which is likely to cause errors

**Comment by radziej** [comment]
A solution for automating the selection of datastreams was implemented beforehand. Confusion with the data and mc skimming config has lead to the mc config being used for data skimming. To prevent future issues like these, additional documentation has been added to the top of the config files.

36939d9e8319d126dc04924e8825b146de9a1b44
f61641a3c6da2445c7198a006153b1b2f5fa33de
