### ISSUE TITLE
Remove the isGlobal muon requirement

### ISSUE THREAD

**Issue by serdweg** [Aachen-3A/PxlSkimmer#8]
At the moment all muons are required to be global Muons, why? To be removed:
https://github.com/Aachen-3A/PxlSkimmer/blob/master/Skimming/src/PxlSkimmer_miniAOD.cc#L2709

**Comment by pmillet** [comment]
done
details: https://github.com/Aachen-3A/PxlSkimmer/commit/6ab879f91f6e8444264ca5ae5f92c8d70274520c
